# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quiz_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quiz_ios
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.2.1'
  pod 'Kingfisher', '~> 6.0'

end
